### ISSUE TITLE
No update to shipped hardware

### ISSUE THREAD

**Issue by albill** [OpenBCI/Spiderclaw#7]
The README notes that there will be a December update to match the shipped hardware. Well, I've received my shipped hardware but there is no update. I'd like to see the STL files updated so I can print a Spiderclaw that fits my hardware.

**Comment by albill** [comment]
Great, so you just "fixed" the README to move the time out. It doesn't address the fact that there is no 3D printable design that works with the hardware we all have now.

**Comment by conorrussomanno** [comment]
Hi aibill,

We're working to get one up here as soon as possible. Right now our priority is making sure everyone gets their OpenBCI tech. Once we've exited fulfillment, it's Spiderclaw time!

Feel free to join in Forum to see who else is working on the 3D-printable headset challenge in the meantime though.

Best,

Conor
